/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.admnizam.kotlin

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
}
